### ISSUE TITLE
Symfony 4 compatibility

### ISSUE THREAD

**Issue by dsuurlant** [TijmenWierenga/Bogus#2]
I'd love to use this library in a SF4 project, but unfortunately it's not compatible because of the symfony/yaml dependency. SF4 also changed the file extension to _yaml_ instead of _yml_.

**Comment by TijmenWierenga** [comment]
Same for me! I'll update the library and probably remove the Yaml dependency. Thanks for creating an issue!

**Comment by TijmenWierenga** [comment]
Closing this issue for now since Symfony 4 compatibility is restored.
